model:
  name: "mistral:7b-instruct-v0.3-q4_K_M"
  path: ""

api_keys:
  alpha_vantage: ""
  finnhub: ""
  news: ""

# tickers:
#   AAPL: "Apple Inc."
#   TSLA: "Tesla Inc."#   GOOGL: "Alphabet Inc."
